<h1> Ajouter un nouveau Cours</h1>

<?php if (!empty($errors)):?>
    <section class="errors">
        <p><?=$errors?></p>
    </section>
<?php endif;?>
<form class="generic-form" method="post">
	<ul>
		<li>
			<label for="title">Titre du Cours : </label>
			<input type="text" name="title" id="title">
		</li>
		<li>
			<label for="content">Contenu du Cours : </label>
            <textarea name="content" id="content"></textarea>
		</li>
		<li>
			<label for="category">Catégorie :</label>
			<select name="category" id="category">
				<option value="1">HTML</option>
				<option value="2">PHP</option>
				<option value="3">CSS</option>
				<option value="4">Javascript</option>
				<option value="5">MySQL</option>
			</select>
		</li>
	</ul>
	<input type="submit" value="Ajouter le cours" name="addCourse">
</form>
<script type="text/javascript">
    tinymce.init({
        selector: 'textarea',
        height: 350,
        theme: 'modern',
        plugins: 'print preview fullpage powerpaste searchreplace autolink directionality advcode visualblocks visualchars fullscreen image link media template codesample table charmap pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount tinymcespellchecker a11ychecker imagetools mediaembed  linkchecker contextmenu colorpicker textpattern help',
        toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
        image_advtab: true,
        templates: [
            { title: 'Test template 1', content: 'Test 1' },
            { title: 'Test template 2', content: 'Test 2' }
        ],
        content_css: [
            '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
            '//www.tinymce.com/css/codepen.min.css'
        ]
    });
</script>