
<header class="flex flex-wrap align-center">
    <div class="stage">

        <a href="index.php?page=home" id="logo"><figure class="ball"><span class="shadow"></span></figure></a>
    </div>

    <div id="user-nav">
		<?php if(session_status() != PHP_SESSION_NONE ):?>

			<?php if($userSession->isLogged()):?>

                <a href="index.php?page=logout" >Déconnexion </a>
			<?php else: ?>
                <a href="index.php?page=login" >Connexion </a>
                <a href="index.php?page=register" >Inscription </a>
			<?php endif; ?>
		<?php endif; ?>

    </div>
    <nav>

		<a href="#" id="linkCours" data-menu="coursMenu"><span class="mobile">Cours</span><i class="material-icons ">library_books</i></a>
        <a href="#" data-menu="linksMenu"><span class="mobile">Liens utiles</span><i class="material-icons ">link</i></a>
		<a href="index.php?page=contact"><span class="mobile">Contact</span><i class="material-icons ">contact_phone</i></a>
        <?php if(session_status() != PHP_SESSION_NONE ):?>
            <?php if($userSession->isAdminLogged()):?>
                <a href="#" data-menu="adminMenu"><span class="mobile"> Panneau Admin</span><i class="material-icons ">gesture</i></a>
            <?php endif; ?>
		<?php endif; ?>
        <form id="search_bar">
            <i class="material-icons" id="btn_search">search</i>
            <input type="text" placeholder="Rechercher" name="search" class="search">

        </form>
    </nav>



    <div id="coursMenu" class="flex hidden space-around absolute" data-submenu data-over="false">
		<div class="flex flex-column">
			<a href="index.php?page=courses&subject=html" class="color-white sub-menu">HTML</a>
		</div>
		<div class="flex flex-column">
			<a href="index.php?page=courses&subject=php" class="color-white sub-menu">PHP</a>
		</div>
		<div class="flex flex-column">
			<a  href="index.php?page=courses&subject=css" class="color-white sub-menu">CSS</a>
		</div>
		<div class="flex flex-column">
			<a href="index.php?page=courses&subject=javascript"  class="color-white sub-menu">Javascript</a>
		</div>
		<div class="flex flex-column">
			<a href="index.php?page=courses&subject=mysql"  class="color-white sub-menu">MySQL</a>
		</div>
	</div>
	<div id="linksMenu" class="flex hidden  space-around absolute" data-submenu data-over="false">
		<div class="flex flex-column">
			<a href="index.php?page=links&subject=html" class="color-white sub-menu">HTML</a>
		</div>
		<div class="flex flex-column">
			<a href="index.php?page=links&subject=php" class="color-white sub-menu">PHP</a>
		</div>
		<div class="flex flex-column">
			<a href="index.php?page=links&subject=css" class="color-white sub-menu">CSS</a>
		</div>
		<div class="flex flex-column">
			<a href="index.php?page=links&subject=javascript" class="color-white sub-menu">Javascript</a>
		</div>
		<div class="flex flex-column">
			<a href="index.php?page=links&subject=mysql" class="color-white sub-menu">MySQL</a>
		</div>
		<div class="flex flex-column">
			<a href="index.php?page=links&subject=other" class="color-white sub-menu">Autres</a>
		</div>
	</div>
	<?php if(session_status() != PHP_SESSION_NONE ):?>

        <?php if($userSession->isAdminLogged()):?>
            <div id="adminMenu" class="flex hidden space-around absolute" data-submenu data-over="false">
                <div class="flex flex-column">
                    <a href="index.php?page=admin&action=addCourse" class="color-white sub-menu">Ajouter un cours</a>
                </div>
                <div class="flex flex-column">
                    <a href="index.php?page=admin&action=manageCourse" class="color-white sub-menu">Gerer les cours</a>
                </div>
                <div class="flex flex-column">
                    <a href="index.php?page=admin&action=addLink" class="color-white sub-menu">Ajouter un lien</a>
                </div>
                <div class="flex flex-column">
                    <a href="index.php?page=admin&action=manageLink" class="color-white sub-menu">Gerer les liens</a>
                </div>

            </div>
        <?php endif; ?>
    <?php endif; ?>

</header>