<!doctype html>

<html lang="fr">

    <head>

        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Feuilles de style -->
        <link href="www/css/normalize-3.0.3.min.css" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="www/css/style.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
              rel="stylesheet">

        <!-- Scripts -->
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
        <script src="www/js/tinymce/tinymce.min.js"></script>
        <script src="www/js/main.js"></script>
        <script src="www/js/FormFilter.class.js"></script>
        <title>Cours de Dev</title>

    </head>

    <body>

        <?php include "www/header.phtml" ?>

        <main>
        <?php include "www/$page.phtml"?>
        </main>

    </body>

</html>