
<?php if (!empty($errors)):?>
    <section class="errors">
        <p><?=$errors?></p>
    </section>
<?php endif;?>
<?php if($category !== ""):?>
	<h1 class="text-center">Les liens utiles pour <?= strtoupper($category) ?></h1>
<?php endif;?>

<!-- On affiche la liste des cours si aucun cour n'est cliqué -->
<?php foreach($links as $link):?>
    <article class="scene scene--card">
        <a href="<?=$link['content']?>" target="_blank">
            <div class="card">
                <div class="card__face card__face--front">
                    <p class="full-width size25"><?= $link['title']?></p>


                </div>
                <div class="card__face card__face--back">
                    <p class="full-width content"><?= $link['content']?></p>
                    <p class="over-card">Ouvrir le lien </p>
                </div>
            </div>
        </a>

    </article>
<?php endforeach;?>

