
<h1>Recherche de "<?= $search ?>" dans les cours et liens</h1>

<?php if (!empty($errors)):?>
    <section class="errors">
        <p><?=$errors?></p>
    </section>
<?php endif;?>
<?php if(!empty($courses)):?>
<section>
	<h2>Cours</h2>
	<?php foreach($courses as $course):?>
        <article class="scene scene--card">
            <a href="?page=courses&id=<?= $course['id']?>">
                <div class="card">
                    <div class="card__face card__face--front">
                        <p class="full-width size25"><?= $course['title']?></p>


                    </div>
                    <div class="card__face card__face--back">
                        <div class="full-width content"><?= $course['content']?></div>
                        <p class="over-card"> Lire la suite </p>
                    </div>
                </div>
            </a>

        </article>


	<?php endforeach;?>
</section>
<?php endif;?>
<?php if (!empty($links)):?>
<section>
	<h2>Liens</h2>
	<?php foreach($links as $link):?>
        <article class="scene scene--card">
            <a href="<?=$link['content']?>" target="_blank">
                <div class="card">
                    <div class="card__face card__face--front">
                        <p class="full-width size25"><?= $link['title']?></p>


                    </div>
                    <div class="card__face card__face--back">
                        <p class="full-width content"><?= $link['content']?></p>
                        <p class="over-card"> Lire la suite </p>
                    </div>
                </div>
            </a>

        </article>

	<?php endforeach;?>
</section>
<?php endif;?>